### PR TITLE
fix: Support bad paths

### PR DESCRIPTION
**Pull request by takusuman**

### CODE REVIEW

**Comment by takusuman** [comment]
Still need some testing on my part.

**Comment by takusuman** [comment]
It works, but it fails at the outsourced (gmp, mpfr, etc) part:

```console
# [...]
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
configure: error: "/media/luiz/Novo Volume/mussel/builds/cross-gcc/gmp" directory shall not contain any space.
checking whether the C compiler works... make: *** [Makefile:5626: configure-mpfr] Error 1
# [...]
```

Eh, funny. But it's not our fault, which rocks, I guess.

**Comment by takusuman** [comment]
Sure, it still works. I think it's pretty much done.

**Comment by firasuke** [comment]
Looks good to me.

We need more testing, perhaps make use of Travis CI..

**Comment by takusuman** [comment]
> We need more testing, perhaps make use of Travis CI..

I don't know a lot about CI, but would Actions work?

**Comment by firasuke** [comment]
> > We need more testing, perhaps make use of Travis CI..
> 
> I don't know a lot about CI, but would Actions work?

I think Actions would work as well.

**Comment by takusuman** [comment]
> I think Actions would work as well.

Would you mind if I propose an Actions file?

**Comment by firasuke** [comment]
> > I think Actions would work as well.
> 
> Would you mind if I propose an Actions file?

Sure that would be a good starting point.

**Pull request merged**
