### PR TITLE
fix: 'trap: ERR: bad trap' on dash.

### PR DESCRIPTION
**Pull request by takusuman**

### CODE REVIEW

**Comment by firasuke** [comment]
Let me know when this draft is ready to be merged.

**Comment by takusuman** [comment]
> Let me know when this draft is ready to be merged.

Sure, I will only test it thoroughly before pushing because I don't want bugs to happen this time.

**Comment by takusuman** [comment]
@firasuke Well, I've tested it, it only fail()s where it supposed to in normal situations.
If you wish, you can test it here with ``pdksh`` and other shells, or maybe see if it fails properly.
By the way, funnily enough, you __can__ use functions and variables in ``trap``, but after declaring the function. It seems like nobody said this on StackOverflow nor other forums.

**Comment by firasuke** [comment]
> @firasuke Well, I've tested it, it only fail()s where it supposed to in normal situations. If you wish, you can test it here with `pdksh` and other shells, or maybe see if it fails properly. By the way, funnily enough, you **can** use functions and variables in `trap`, but after declaring the function. It seems like nobody said this on StackOverflow nor other forums.

Interesting, though I'd rather if we avoided any weird or unintended behaviors/side-effects.

I'll perform some tests with different shells and report back.

**Comment by takusuman** [comment]
> Interesting, though I'd rather if we avoided any weird or unintended behaviors/side-effects.

Well, it __is__ indeed POSIX compatible and it failed when something in fact failed, so I doubt there's any undefined payloads here.

**Comment by firasuke** [comment]
> ... but I don't think there's any way to get better than this inside POSIX restraints.

I agree. Merged!

**Pull request merged**
